// Composables
import { createRouter, createWebHistory } from 'vue-router/auto'
import { setupLayouts } from 'virtual:generated-layouts'
import { routes as autoGeneratedRoutes } from 'vue-router/auto-routes'
import HomePage from '../components/HomePage.vue'
import LoginPage from '@/components/LoginPage.vue'
import RegisterPage from '../components/RegisterPage.vue'
// Manually defined routes
const customRoutes = [
  
  {
    path: '/home',
    name: 'HomePage',
    component: HomePage
  },

  {
    path: '/register',
    name: 'RegisterPage',
    component: RegisterPage
  }
]

// Merge custom routes with auto-generated routes
const routes = setupLayouts([...autoGeneratedRoutes, ...customRoutes])

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes
})

router.isReady().then(() => {
  localStorage.removeItem('vuetify:dynamic-reload')
})


export default router
